name: Example - Create S3 Bucket

on:
  push:
    branches:
      - main
env: 
  bucket_name: roberto

jobs:
  create-bucket:
    permissions:
      id-token: write # Required for AWS authentication
      contents: read
      
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.ROLE_ARN }}
        role-session-name: ${{ github.actor }}
    
    - uses: alonch/actions-aws-backend-setup@main
      with: 
        instance: bucket-demo 

    - name: Create S3 Bucket
      uses: realsensesolutions/actions-aws-bucket@main
      id: bucket
      with:
        name: ${{ env.bucket_name }}